Repository DedalusDIIT/cornerstone3D, pull requests merged in 2024-10, with the labels that each got.

#9 UCC: Sync fork
  .github/workflows/playwright.yml
  CHANGELOG.md
  addOns/externals/dicom-microscopy-viewer/CHANGELOG.md
  addOns/externals/dicom-microscopy-viewer/package.json
  commit.txt
  common/reviews/api/core.api.md
  lerna.json
  packages/adapters/CHANGELOG.md
  packages/adapters/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/RenderingEngine/StackViewport.ts
  packages/core/src/enums/Events.ts
  packages/core/src/types/EventTypes.ts
  packages/core/src/types/IViewport.ts
  packages/dicomImageLoader/CHANGELOG.md
  packages/dicomImageLoader/package.json
  packages/dicomImageLoader/src/imageLoader/internal/streamRequest.ts
  packages/dicomImageLoader/src/imageLoader/isColorConversionRequired.ts
  packages/docs/CHANGELOG.md
  packages/docs/package.json
  packages/nifti-volume-loader/CHANGELOG.md
  packages/nifti-volume-loader/package.json
  packages/streaming-image-volume-loader/CHANGELOG.md
  packages/streaming-image-volume-loader/package.json
  packages/tools/CHANGELOG.md
  packages/tools/examples/stackManipulationTools/index.ts
  packages/tools/package.json
  packages/tools/src/utilities/planarFreehandROITool/smoothAnnotation.ts
  packages/tools/src/utilities/scroll.ts
  version.json
  version.txt
Labels: 1 min review, uncomplex code change

#11 Remove RGBA check
  packages/dicomImageLoader/src/imageLoader/colorSpaceConverters/convertRGBColorByPixel.ts
  packages/dicomImageLoader/src/imageLoader/convertColorSpace.ts
  packages/dicomImageLoader/src/imageLoader/createImage.ts
Labels: 1 min review, missing-jira

#12 Fix Image Loader - Part 2
  packages/dicomImageLoader/package.json
  packages/dicomImageLoader/src/imageLoader/colorSpaceConverters/convertRGBColorByPixel.ts
  packages/dicomImageLoader/src/imageLoader/convertColorSpace.ts
  packages/dicomImageLoader/src/imageLoader/createImage.ts
Labels: 1 min review, missing-jira

#14 DVISA-2440: WADO RS support
  packages/dicomImageLoader/package.json
  packages/dicomImageLoader/src/imageLoader/wadors/register.ts
  packages/dicomImageLoader/src/imageLoader/wadouri/dataSetCacheManager.ts
  packages/dicomImageLoader/src/imageLoader/wadouri/loadImage.ts
  packages/dicomImageLoader/src/imageLoader/wadouri/parseImageId.ts
  packages/dicomImageLoader/src/imageLoader/wadouri/retrieveMultiframeDataset.ts
Labels: 1 min review
